### PR TITLE
Merge from a fork

### PR DESCRIPTION
**Pull request by slitvinov**
- pip package for korali and DComEx python scripts
- new MSolve bio solver
- new tests and examples
- bug fixes and extensions in korali
- update of installation scripts and CI/CD pipeline
- analysis scripts and notebooks

### CODE REVIEW

**Comment by bcumming** [comment]
Before merging, is it possible to get the CI/CD to pass?

**Comment by slitvinov** [comment]
I am working on fixing it, but the pipeline fails very [early in the process](https://gitlab.com/cscs-ci/ci-testing/webhook-ci/mirrors/3810120997072523/5356285708783511/-/jobs/6981482262). Could it be a temporary issue with docker.io?
```Checking write permission for jfrog.svc.cscs.ch/docker-ci-ext/3810120997072523/public/base/dcomex-framework:8f1f61fc202da316
Setting build argument NUM_PROCS=64
STEP 1/7: FROM docker.io/nvidia/cuda:11.2.0-cudnn8-devel-ubuntu20.04
Trying to pull docker.io/nvidia/cuda:11.2.0-cudnn8-devel-ubuntu20.04...
Error: creating build container: initializing source docker://nvidia/cuda:11.2.0-cudnn8-devel-ubuntu20.04: reading manifest 11.2.0-cudnn8-devel-ubuntu20.04 in docker.io/nvidia/cuda: manifest unknown
```

**Comment by finkandreas** [comment]
Nvidia has removed this container from dockerhub. Let's try with `cuda:11.2.2-cudnn8-devel-ubuntu20.04`

**Comment by slitvinov** [comment]
> Nvidia has removed this container from dockerhub. Let's try with `cuda:11.2.2-cudnn8-devel-ubuntu20.04`

Thanks. Passes now.

**Review by bcumming — APPROVED** [review]

**Comment by bcumming** [comment]
Before merging, could you please write a description for the PR that describes the changes made?
It doesn't have to be very detailed - just a high level summary of the key changes, so that we can give this (very large) commit a meaningful description.
@slitvinov

**Comment by slitvinov** [comment]
> Before merging, could you please write a description for the PR that describes the changes made? It doesn't have to be very detailed - just a high level summary of the key changes, so that we can give this (very large) commit a meaningful description. @slitvinov

@bcumming Thank you. I've squached the commits into several ones and added the PR description.

**Pull request merged**
